# Generated by Django 5.0.6 on 2024-06-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('tool', models.CharField(max_length=200)),
                ('specs', models.CharField(max_length=200)),
            ],
        ),
    ]
